---
title: "4.2.rnaseq_rf"
author: "Erica Ryu"
date: "10/29/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 4.2 Random Forest

The purpose of this script is to perform random forest with the RNAseq data

## load packages
```{r}
library(randomForest)
library(reshape2)
library(ggplot2)
```

## load data
```{r}
counts_lmm <- read.csv("output/counts_regress.csv", header = TRUE, row.names = 1)
metadata <- read.csv("data/RNA_metadata.csv", header = TRUE)
```

## subset data to each condition
```{r}
# subset to sequenced libraries first
metadata_lp <- metadata[!is.na(metadata$s.SequencingBatch), ]

# scale and center covariates
# metadata_lp$age_scaled <- scale(metadata_lp$i.Age, center = TRUE)
# metadata_lp$RIN_scaled <- scale(metadata_lp$ex.RINscore, center = TRUE)
# metadata_lp$lp_batch <- as.factor(metadata_lp$p.LibraryBatch)

# subset to disease
metadata_disease <- metadata_lp[grepl('Right Colon', metadata_lp$i.Specimen), ]

counts_lmm_disease <- subset(counts_lmm, rownames(counts_lmm) %in% metadata_disease$p.LibraryID)
  
## set row order
metadata_disease <- metadata_disease[order(metadata_disease$p.LibraryID, decreasing = FALSE),]

# subset to specimen
metadata_spec <- metadata_lp[grepl('Crohns', metadata_lp$i.Disease), ]

counts_lmm_spec <- subset(counts_lmm, rownames(counts_lmm) %in% metadata_spec$p.LibraryID)

## set row order
metadata_spec <- metadata_spec[order(metadata_spec$p.LibraryID, decreasing = FALSE),]
```

## random forest
```{r}
# disease
## check order
identical(rownames(counts_lmm_disease), metadata_disease$p.LibraryID)

## add disease info
counts_lmm_disease$disease <- metadata_disease$i.Disease

## check for balance
table(counts_lmm_disease$disease)

## rf
set.seed(100)
rf_disease <- randomForest(x = counts_lmm_disease[, colnames(counts_lmm_disease) != "disease"],
                   y = as.factor(counts_lmm_disease$disease))
print(rf_disease)

#                Type of random forest: classification
#                      Number of trees: 500
# No. of variables tried at each split: 187
# 
#         OOB estimate of  error rate: 14.29%
# Confusion matrix:
#                   Colorectal Cancer Crohns class.error
# Colorectal Cancer                 9      6  0.40000000
# Crohns                            2     39  0.04878049

# specimen
## check order
identical(rownames(counts_lmm_spec), metadata_spec$p.LibraryID)

## add disease info
counts_lmm_spec$specimen <- metadata_spec$i.Specimen

## check for balance
table(counts_lmm_spec$specimen)

## rf
set.seed(100)
rf_spec <- randomForest(x = counts_lmm_spec[, colnames(counts_lmm_spec) != "specimen"],
                   y = as.factor(counts_lmm_spec$specimen))
print(rf_spec)

#         OOB estimate of  error rate: 33.58%
# Confusion matrix:
#                Cecum Right Colon Terminal Ileum class.error
# Cecum             36          11              2  0.26530612
# Right Colon       24          13              4  0.68292683
# Terminal Ileum     2           2             40  0.09090909

## redo without weird samples
counts_lmm_spec_filt <- subset(counts_lmm_spec, !(rownames(counts_lmm_spec) %in% c("LP047", "LP114", "LP155", "LP005", "LP157", "LP158", "LP159")))

## check for balance
table(counts_lmm_spec_filt$specimen)

## rf
set.seed(100)
rf_spec_filt <- randomForest(x = counts_lmm_spec_filt[, colnames(counts_lmm_spec_filt) != "specimen"],
                   y = as.factor(counts_lmm_spec_filt$specimen))
print(rf_spec_filt)

#         OOB estimate of  error rate: 32.28%
# Confusion matrix:
#                Cecum Right Colon Terminal Ileum class.error
# Cecum             36          10              1  0.23404255
# Right Colon       27          10              2  0.74358974
# Terminal Ileum     1           0             40  0.02439024

# 


#         OOB estimate of  error rate: 25.38%
# Confusion matrix:
#               Cecum RightColon TerminalIleum class.error
# Cecum            37          9             2  0.22916667
# RightColon       16         21             4  0.48780488
# TerminalIleum     1          1            39  0.04878049
```

## plot
```{r}
# disease
## extract the confusion matrix
cm_disease <- as.data.frame(rf_disease$confusion)

## remove class error
cm_disease <- cm_disease[, !(colnames(cm_disease) %in% c("class.error"))]

## convert to percentage based on row total
cm_disease_percent <- cm_disease/rowSums(cm_disease)

## convert format
cm_disease_df <- melt(as.data.frame(cm_disease_percent))

## fix names 
colnames(cm_disease_df) <- c("Predicted", "Count")

## add true label
cm_disease_df$True <- rep(c("Colorectal Cancer", "Crohns"), times = 2)

## reorder for convenience
cm_disease_df <- cm_disease_df[, c("True", "Predicted", "Count")]

ggplot(cm_disease_df, aes(x = True, y = Predicted, fill = Count)) +
  geom_tile() +
  geom_text(aes(label = round(Count, 2)))+
  scale_fill_gradient(low="white", high="#009194", limits=c(0,1))+
  labs(x = "True Label",y = "Predicted Label")

# specimen
## extract the confusion matrix
cm_spec <- as.data.frame(rf_spec$confusion)

## remove class error
cm_spec <- cm_spec[, !(colnames(cm_spec) %in% c("class.error"))]

## convert to percentage based on row total
cm_spec_percent <- cm_spec/rowSums(cm_spec)

## convert format
cm_spec_df <- melt(as.data.frame(cm_spec_percent))

## fix names 
colnames(cm_spec_df) <- c("Predicted", "Count")

## add true label
cm_spec_df$True <- rep(c("Cecum", "Right Colon", "Terminal Ileum"), times = 3)

## reorder for convenience
cm_spec_df <- cm_spec_df[, c("True", "Predicted", "Count")]

ggplot(cm_spec_df, aes(x = True, y = Predicted, fill = Count)) +
  geom_tile() +
  geom_text(aes(label = round(Count, 2)))+
  scale_fill_gradient(low="white", high="#009194", limits=c(0,1))+
  labs(x = "True Label",y = "Predicted Label")

# specimen filtered
## extract the confusion matrix
cm_spec_filt <- as.data.frame(rf_spec_filt$confusion)

## remove class error
cm_spec_filt <- cm_spec_filt[, !(colnames(cm_spec_filt) %in% c("class.error"))]

## convert to percentage based on row total
cm_spec_filt_percent <- cm_spec_filt/rowSums(cm_spec_filt)

## convert format
cm_spec_filt_df <- melt(as.data.frame(cm_spec_filt_percent))

## fix names 
colnames(cm_spec_filt_df) <- c("Predicted", "Count")

## add true label
cm_spec_filt_df$True <- rep(c("Cecum", "Right Colon", "Terminal Ileum"), times = 3)

## reorder for convenience
cm_spec_filt_df <- cm_spec_filt_df[, c("True", "Predicted", "Count")]

ggplot(cm_spec_filt_df, aes(x = True, y = Predicted, fill = Count)) +
  geom_tile() +
  geom_text(aes(label = round(Count, 2)))+
  scale_fill_gradient(low="white", high="#009194", limits=c(0,1))+
  labs(x = "True Label",y = "Predicted Label")
```

